version: '3'

services:
  mongodb:
    container_name: mgp_mongo
    image: mongo:latest
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mgp
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

networks:
  default:

volumes:
  mongodb: